version: '3.7'

services:
  nginx:
    image: nginx
    container_name: esnad_nginx
    volumes:
      - ./app:/var/www/app
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - nginx_node_mysql

  node:
    build:
      context: .
    container_name: esnad_node
    ports:
      - 3000:3000
    depends_on:
      - mysql
    volumes:
      - ./app:/var/www/app
    networks:
      - nginx_node_mysql

  mysql:
    image: mariadb:10.7.1
    container_name: esnad_mysql
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - nginx_node_mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: esnad_phpmyadmin
    environment:
      PMA_HOST: mysql
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - nginx_node_mysql

networks:
  nginx_node_mysql:
    external: true
